config/routes.rb
Rails.application.routes.draw do
  # CREATE
  # get 'restaurants/new',      to: "restaurants#new", as: 'new_restaurant'
  # post 'restaurants',         to: "restaurants#create"
  # # READ
  # get 'restaurants',          to: "restaurants#index"
  # get 'restaurants/:id',      to: "restaurants#show"
  # # UPDATE
  # get 'restaurants/:id/edit', to: "restaurants#edit", as: 'edit_restaurant'
  # patch 'restaurants/:id',    to: "restaurants#update"
  # # DELETE
  # delete 'restaurants/:id',   to: "restaurants#destroy"
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :stars %>
  <%= f.number_field :stars %>

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant_path(restaurant) do %>
        <h3><%= restaurant.name %></h3>
      <% end %>
      <%= link_to "Edit this Restaurant", edit_restaurant_path(restaurant) %>
      <%= link_to "Delete this Restaurant", restaurant_path(restaurant), method: 'delete' %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h4><%= @restaurant.address %></h4>
<h4><%= '*' * @restaurant.stars %></h4>